### ISSUE TITLE
카메라 이동을 직진할때 양옆으로 이동하는 것을 빼야하나?

### ISSUE THREAD

**Issue by Lhyejin** [madmonkey9/Shooo-Bomb#15]
카메라 컨트롤러에서 진행방향에 따라 카메라가 움직이기 때문에 직진에서 양옆으로 움직여도 카메라가 움직인다. 터치슬라이드를 할 때만 움직이게 만들까요?

**Comment by madmonkey9** [comment]
슬라이드로 방향전환시만 카메라 이동하게 해주세요~
